EntityBundle\Entity\AuthorizedComments:
    type: entity
    table: null
    repositoryClass: EntityBundle\Repository\AuthorizedCommentsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        comment:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
