EntityBundle\Entity\Comments:
    type: entity
    table: null
    repositoryClass: EntityBundle\Repository\CommentsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUser:
            type: integer
            column: IdUser
        idAuthorizedComment:
            type: integer
            column: IdAuthorizedComment
        idArticle:
            type: integer
            column: IdArticle
    lifecycleCallbacks: {  }
