<?php

namespace EntityBundle\Repository;

/**
 * ArticleARRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleARRepository extends \Doctrine\ORM\EntityRepository
{
}
