<?php

namespace EntityBundle\Repository;

/**
 * ArticleFRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleFRRepository extends \Doctrine\ORM\EntityRepository
{
}
